### ISSUE TITLE
Problems when I run the api with docker

### ISSUE THREAD

**Issue by antojsh** [azanium/generator-astro#4]
```$ docker-compose -f docker-compose.yml -f docker-compose.dev.yml up
Starting portal-fintra_postgres_1 ... done
Starting portal-fintra_migrations_1 ... done
Starting portal-fintra_portal-fintra_1 ... done
Attaching to portal-fintra_postgres_1, portal-fintra_migrations_1, portal-fintra_portal-fintra_1
postgres_1       | LOG:  database system was interrupted; last known up at 2019-01-16 15:31:33 UTC
postgres_1       | LOG:  database system was not properly shut down; automatic recovery in progress
migrations_1     | yarn run v1.5.1
postgres_1       | LOG:  redo starts at 0/14F1AC0
postgres_1       | LOG:  invalid record length at 0/150A790: wanted 24, got 0
postgres_1       | LOG:  redo done at 0/150A768
postgres_1       | LOG:  last completed transaction was at log time 2019-01-16 15:31:36.828492+00
migrations_1     | $ sequelize db:migrate
postgres_1       | LOG:  MultiXact member wraparound protections are now enabled
postgres_1       | LOG:  database system is ready to accept connections
postgres_1       | LOG:  autovacuum launcher started
portal-fintra_1  | yarn run v1.5.1
portal-fintra_1  | $ NODE_ENV=development nodemon ./src/index.js
migrations_1     |
migrations_1     | Sequelize CLI [Node: 9.11.2, CLI: 5.3.0, ORM: 4.41.2]
migrations_1     |
migrations_1     | Loaded configuration file "src/config/database.js".
migrations_1     | Wed, 16 Jan 2019 15:37:52 GMT sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators at node_modules/sequelize/lib/sequelize.js:242:13
migrations_1     | No migrations were executed, database schema was already up to date.
migrations_1     | Done in 6.45s.
portal-fintra_1  | [nodemon] 1.18.7
portal-fintra_1  | [nodemon] to restart at any time, enter `rs`
portal-fintra_1  | [nodemon] watching: *.*
portal-fintra_1  | [nodemon] starting `node ./src/index.js`
portal-fintra_migrations_1 exited with code 0
portal-fintra_1  | info: Starting up booting tasks...
portal-fintra_1  | info: Server started on port 1447 (development)
portal-fintra_1  | { Error: connect ECONNREFUSED 169.254.169.254:80
portal-fintra_1  |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1174:14)
portal-fintra_1  |   message: 'Missing credentials in config',
portal-fintra_1  |   errno: 'ECONNREFUSED',
portal-fintra_1  |   code: 'CredentialsError',
portal-fintra_1  |   syscall: 'connect',
portal-fintra_1  |   address: '169.254.169.254',
portal-fintra_1  |   port: 80,
portal-fintra_1  |   time: 2019-01-16T15:38:01.792Z,
portal-fintra_1  |   originalError:
portal-fintra_1  |    { message: 'Could not load credentials from any providers',
portal-fintra_1  |      errno: 'ECONNREFUSED',
portal-fintra_1  |      code: 'CredentialsError',
portal-fintra_1  |      syscall: 'connect',
portal-fintra_1  |      address: '169.254.169.254',
portal-fintra_1  |      port: 80,
portal-fintra_1  |      time: 2019-01-16T15:38:01.792Z,
portal-fintra_1  |      originalError:
portal-fintra_1  |       { errno: 'ECONNREFUSED',
portal-fintra_1  |         code: 'ECONNREFUSED',
portal-fintra_1  |         syscall: 'connect',
portal-fintra_1  |         address: '169.254.169.254',
portal-fintra_1  |         port: 80,
portal-fintra_1  |         message: 'connect ECONNREFUSED 169.254.169.254:80' } } }

**Comment by azanium** [comment]
You need to remove the cloudwatch inside logger util.
For this to work you need to have a valid either:

1. EC2 instance with attach IAM role
2. AWS Profile locally
3. AWS Access Key ID and Secret on process.env

As this is not an issue, I will close this.
